<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class orderMealsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $orderMeals = [
            //Dla zamówień webowych
            [
                'OrderId' => 1, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 1, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 1, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 1, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 2, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 2, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 2, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 3, 
                'MealId' => 117,
                'OrderDate' => "2022-02-09 01:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 4, 
                'MealId' => 124,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 4, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 4, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 5, 
                'MealId' => 118,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 5, 
                'MealId' => 119,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 5, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 5, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 6, 
                'MealId' => 134,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 6, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 6, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 7, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 7, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 7, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 7, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 8, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 8, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 8, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 9, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 10, 
                'MealId' => 134,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 10, 
                'MealId' => 117,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 10, 
                'MealId' => 135,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 11, 
                'MealId' => 129,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 11, 
                'MealId' => 130,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 12, 
                'MealId' => 124,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 12, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 12, 
                'MealId' => 135,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 13, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 14, 
                'MealId' => 134,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 14, 
                'MealId' => 117,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 14, 
                'MealId' => 135,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 15, 
                'MealId' => 118,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 15, 
                'MealId' => 119,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 15, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 15, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 16, 
                'MealId' => 124,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 16, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 16, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 17, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 03:26:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 18, 
                'MealId' => 134,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 18, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 18, 
                'MealId' => 135,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            //dla zamówień na miejscu
            [
                'OrderId' => 19, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 19, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 19, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 19, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 20, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 20, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 20, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 21, 
                'MealId' => 117,
                'OrderDate' => "2022-02-09 01:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 22, 
                'MealId' => 124,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 22, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 22, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 23, 
                'MealId' => 118,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 23, 
                'MealId' => 119,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 23, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 23, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 24, 
                'MealId' => 134,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 24, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 24, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 25, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 25, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 25, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 25, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 26, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 26, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 26, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 27, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 28, 
                'MealId' => 134,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 28, 
                'MealId' => 117,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 28, 
                'MealId' => 135,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 29, 
                'MealId' => 129,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 29, 
                'MealId' => 130,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 30, 
                'MealId' => 124,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 30, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 30, 
                'MealId' => 135,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 31, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 32, 
                'MealId' => 134,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 32, 
                'MealId' => 117,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 32, 
                'MealId' => 135,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 33, 
                'MealId' => 118,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 33, 
                'MealId' => 119,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 33, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 33, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 34, 
                'MealId' => 124,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 34, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 34, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 35, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 03:26:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 36, 
                'MealId' => 134,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 36, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 36, 
                'MealId' => 135,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            //dla zamówień na wynos
            [
                'OrderId' => 37, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 37, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 37, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 37, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 38, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 38, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 38, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 39, 
                'MealId' => 117,
                'OrderDate' => "2022-02-09 01:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 40, 
                'MealId' => 124,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 40, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 40, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 41, 
                'MealId' => 118,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 41, 
                'MealId' => 119,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 41, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 41, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 22:20:10",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 42, 
                'MealId' => 134,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 42, 
                'MealId' => 117,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 42, 
                'MealId' => 135,
                'OrderDate' => "2022-02-01 23:03:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 43, 
                'MealId' => 118,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 43, 
                'MealId' => 119,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 43, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 43, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 44, 
                'MealId' => 124,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 44, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 44, 
                'MealId' => 135,
                'OrderDate' => "2022-02-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 45, 
                'MealId' => 117,
                'OrderDate' => "2022-02-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 46, 
                'MealId' => 134,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 46, 
                'MealId' => 117,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 46, 
                'MealId' => 135,
                'OrderDate' => "2022-02-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 47, 
                'MealId' => 129,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 47, 
                'MealId' => 130,
                'OrderDate' => "2022-01-11 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 48, 
                'MealId' => 124,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 48, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 48, 
                'MealId' => 135,
                'OrderDate' => "2022-01-11 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 49, 
                'MealId' => 117,
                'OrderDate' => "2022-01-11 03:26:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 50, 
                'MealId' => 134,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 50, 
                'MealId' => 117,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 50, 
                'MealId' => 135,
                'OrderDate' => "2022-01-12 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 51, 
                'MealId' => 118,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 51, 
                'MealId' => 119,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 3,
            ],
            [
                'OrderId' => 51, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 51, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 02:23:40",
                'Status' => 1,
                'Quantity' => 4,
            ],
            [
                'OrderId' => 52, 
                'MealId' => 124,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 52, 
                'MealId' => 117,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 52, 
                'MealId' => 135,
                'OrderDate' => "2022-03-01 03:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 53, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 03:26:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
            [
                'OrderId' => 54, 
                'MealId' => 134,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 54, 
                'MealId' => 117,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 1,
            ],
            [
                'OrderId' => 54, 
                'MealId' => 135,
                'OrderDate' => "2022-03-02 12:23:40",
                'Status' => 1,
                'Quantity' => 2,
            ],
        ];
    
        DB::table('order_meals')->insert($orderMeals);
    }
}